# Generated by Django 4.1.3 on 2023-05-05 21:02

import builtins
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(error_messages={'unique': 'Галерея с таким названием уже существует!'}, max_length=70, unique=True, verbose_name='Название галереи')),
            ],
            options={
                'db_table': 'galleryNews',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(error_messages={'unique': 'Галерея с таким названием уже существует!'}, max_length=70, unique=True, verbose_name='Название галереи')),
            ],
            options={
                'db_table': 'galleryProject',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PhotosProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.ImageField(upload_to=main.models.get_file_path, verbose_name='Путь к картинке')),
                ('Caption', models.CharField(max_length=200, verbose_name='Название картинки')),
                ('Gallery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.galleryproject', verbose_name='Галерея')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PhotosNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.ImageField(upload_to=main.models.get_file_path, verbose_name='Путь картинки')),
                ('Caption', models.CharField(max_length=200, verbose_name='Название картинки')),
                ('Gallery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.gallerynews', verbose_name='Галерея')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(error_messages={'unique': 'Новость с таким названием уже существует!'}, max_length=100, unique=True, verbose_name='Заголовок новости')),
                ('Short_Description', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('Description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('Date_added', models.DateTimeField(default=builtins.pow, verbose_name='Дата публикации')),
                ('Gallery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.gallerynews', verbose_name='Галерея')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
