# Generated by Django 4.1.3 on 2023-05-06 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photosproject',
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='GalleryProject',
        ),
        migrations.DeleteModel(
            name='PhotosProject',
        ),
    ]
