# Generated by Django 4.1.3 on 2023-05-06 02:20

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_photosproject_gallery_delete_galleryproject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.CreateModel(
            name='Ratind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(error_messages={'unique': 'Новость с таким названием уже существует!'}, max_length=100, unique=True, verbose_name='Заголовок новости')),
                ('Short_Description', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('Description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('Date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('Status', models.CharField(choices=[('Убитая дорога', 'Убитая дорога'), ('Локальный дефект', 'Локальный дефект'), ('Локальный дефект исправлен', 'Локальный дефект исправлен'), ('Дорога отремонтирована', 'Дорога отремонтирована')], default='Убитая дорога', max_length=78, verbose_name='Статус')),
                ('Gallery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.gallerynews', verbose_name='Галерея')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
